name: Main

on: push

jobs:
  release:
    name: Publish new release
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '.0')
    runs-on: ubuntu-22.04
    #needs: test_e2e # Publish only if everything else succeeded
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          token: ${{ github.token }}

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changelog }}

      - name: Create release branch
        run: |
          git checkout -b release/$GITHUB_REF_NAME
          git push origin release/$GITHUB_REF_NAME
